### ISSUE TITLE
Narrative component inside of an article reveal

### ISSUE THREAD

**Issue by joe-replin** [cgkineo/adapt-article-reveal#13]
Running into a fun little bug with a fresh install of v2.1.2. If I place a narrative inside of an article reveal, the overall narrative slider reduces down to a very small height. Upon resizing the screen, the narrative corrects itself. It seems as though the narrative isn't properly sizing on page load when inside of an article reveal. After speaking with @tomgreenfield, his advice was to revert the 'onWindowResize' function inside device.js file to a previous iteration and the issue was corrected. @oliverfoster asked to open a ticket here. Below is an example of how the narrative appears.

![reveal and narrative](https://user-images.githubusercontent.com/7740674/27103747-59d10542-504f-11e7-9e5d-5b8f57ab84d9.PNG)

**Comment by oliverfoster** [comment]
thanks @joe-replin

**Comment by oliverfoster** [comment]
suggest using visibility: hidden, overflow: hidden instead of [display:none](https://github.com/cgkineo/adapt-article-reveal/blob/master/js/adapt-article-reveal.js#L50) so that the size of the container is retained.

**Comment by danielstorey** [comment]
https://github.com/danielstorey/adapt-stacklist/issues/12 also relates to this. I'd second Ollie's suggestion except you might also need to use height:0 in conjunction with visibility/overflow:hidden, otherwise the element will still take up space in the DOM. Prob easier to use a class for this.

**Comment by chucklorenz** [comment]
Confirming that the addition of @danielstorey 's article reveal fix ('change resizing trigger') rectified the issue in @joe-replin 's original post.

**Comment by joe-replin** [comment]
Thank you all! What would be the process to get this implemented into the article reveal plug-in itself? I would be happy to close this up once confirmed.

**Comment by oliverfoster** [comment]
merged... sorry @danielstorey i completely missed you'd already done a pr for it... so two prs and a merge conflict later, it's in...

**Comment by danielstorey** [comment]
Haha no worries. Pleased to be of service
