### ISSUE TITLE
Opening any Article within Article Reveal unlocks other Article items (sub-components) in the PLP

### ISSUE THREAD

**Issue by kineoluke** [cgkineo/adapt-article-reveal#4]
Within an Adapt Article Reveal component there are usually multiple Articles; once a user opens an Article, then any (All? Yet to test.) other Article items (sub-components) are unlocked in the Page Level Progress dropdown menu. 

This means the user can use the PLP dropdown menu to navigate to a closed Article. This results in an odd bug whereby since the Article is closed, the position/anchor just keeps getting nudged up the page bit by bit. 
# PLP #PageLevelProgress

@kirsty-hames @salali @danielghost @tomallpress

**Comment by moloko** [comment]
closing, too old
